name: rspec

on:
  push:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'bin/*'
  pull_request:
    branches:
      - main
    paths-ignore:
      - 'docs/**'
      - '*.md'
      - 'bin/*'

jobs:
  rspec:

    runs-on: ubuntu-latest

    services:
      db:
        image: postgres:12.3
        env:
         PG_PASSWORD: password
         POSTGRES_HOST_AUTH_METHOD: trust
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          bundler-cache: true

      - name: Install PostgreSQL client
        run: |
          sudo apt-get -yqq install libpq-dev
      - name: Build App
        env:
          PG_DATABASE: postgres
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: password
          RAILS_ENV: test
          POSTGRES_PORT: 5432
          POSTGRES_HOST_AUTH_METHOD: trust
        run: |
          yarn
          bundle exec rake db:create
          bundle exec rake db:schema:load
          bundle exec rails webpacker:compile
      - name: Run rspec
        env:
          PG_DATABASE: postgres
          PG_HOST: localhost
          PG_USER: postgres
          PG_PASSWORD: password
          RAILS_ENV: test
          POSTGRES_PORT: 5432
          POSTGRES_HOST_AUTH_METHOD: trust
        run: |
          bundle exec rspec